language: ruby
rvm:
  - 1.9.2


before_install:
  - git submodule update --init
bundler_args: --without development
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "rake test[all]"

# whitelist
branches:
  only:
    - master
    - development
    - testing